[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://localhost:54321"

[edge-runtime]
enabled = true
port = 54323

[[edge-runtime.env_vars]]
name = "GEMINI_API_KEY"
value = "YOUR_GEMINI_API_KEY_HERE"

[db]
port = 54322
